### PR TITLE
Added Danish language.

### PR DESCRIPTION
**Pull request by mikkelee**
Simply a translation form the English. I have tested with a couple of local files & it seems to work fine for me.

Thanks for the excellent package!

### CODE REVIEW

**Comment by T-F-S** [comment]
Thank you for adding a Danish translation!

Currently, I'm to busy to process this immediately, but in the near future I would like to add this as you proposed. Also, I want to cite the Danish language inside the documentation with something like 'Danish language provided by Mikkel Eide Eriksen', if this is OK for you.

Thanks again!

**Comment by mikkelee** [comment]
That would be great! 👍

**Comment by T-F-S** [comment]
I integrated your translation into the code and into the documentation. 

Please note that I removed the line
`\gtrset{date format=d/m/yyyy}`
from the translation code, because date formatting should not be part of a translation file - even, if this is the preferred date format for a specific language.

Thank you for your help in improving the package.

**Comment by mikkelee** [comment]
That's fine, no problem. Thanks!

**Comment by T-F-S** [comment]
I made some test examples with different languages. For Danish,
"**before January 1580 in Augsburg**"
becomes
"**før januar 1580 i Augsburg**".

I wonder, if "januar" should not better be written capitalized as "Januar" for Danish?
The same would be true for all long and short month names.

Please, let me know, if the month names should get capital first letters or if they are really written as in the example above.

**Comment by perstar** [comment]
Small letter is correct. I'm not Danish, but I can read that that is what it says in the rather official http://rediger.sproget.dk/raad-og-regler/retskrivningsregler/retskrivningsregler/a7-11-14/a7-12-store-og-sma-bogstaver-i-proprier :+1:
 
>  Månederne og ugedagene og betegnelser på religiøse og nationale højtider og festdage mv. skrives med lille:
> 
>     januar, mandag, påske, pinse, jul, nytår, juleaften, nytårsaften, store bededag, grundlovsdag, mortensaften, sankthansaften, valborg(s)aften, ramadan, yom kippur, mors dag.

(It's the same in Swedish, which is my native language, btw.)

**Comment by T-F-S** [comment]
Thank you for the feedback. I just wanted to be sure that the small letters are used intentionally, before the package gets published on CTAN.

**Comment by mikkelee** [comment]
Another link:

Retskrivningsordbogen (Ortographic Dictionary), 4th ed. (2012), §12 pt. 13c (my translation): "The months and days of the week and names of religious or national holidays etc. are written with a lowercase initial", followed by examples.

https://dsn.dk/retskrivning/retskrivningsregler/a7-11-14/a7-12#12_13_c

Note it also goes for dates such as "25. januar 2017"

**Comment by T-F-S** [comment]
Thanks. I just wanted to be sure that there was no unintionally typo :-)

**Comment by perstar** [comment]
Glad to see this being done right, because at least for Swedish it's often done wrong in localizations. Besides putting capitals there that should have been small it can also be so that the program assumes that every localization of a name of month or weekday will start with capital so nothing is done to make sure there is a capital if it should have capital because of being first, for example as a header with the date.

**Comment by T-F-S** [comment]
I reviewed the idea of a language-dependent date format setting.

Currently, `d.M.yyyy` is the default setting which can be adapted for every tree diagram. Today, I changed this into `typical`, a new value which is language-dependent (it is not on GitHub yet).

Every language setting can define a `typical` date format which should consist of **day**, **month name**, and **year**. For Danish, you could select one of the values listed in Section 7.7 of the documentation (page 173f).

For the time being, from your comments, I put in `d.month yyyy` for Danish, e.g. "2. februar 1640". Please, correct me, if this should be different.

**Comment by mikkelee** [comment]
Excellent, that's the default way of writing full dates in Danish.

~~Some use a comma: "2. februar, 1640" but I don't believe it's required. Let me see if I can find an authoritative quote on that.~~

Added: No comma is correct, see "2. oktober 2003" below; prefixing with "den" (the) is optional.
http://sproget.dk/raad-og-regler/artikler-mv/svarbase/SV00000046

**Pull request merged**
