### PR TITLE
Floruit event

### PR DESCRIPTION
**Pull request by mikkelee**
Hi again!

I'm working on some very sparsely sourced stuff and needed a "floruit" event. I'm not so good at tikz, but the symbol is supposed to resemble a flower (I'm not aware of any widely used symbols other than the fl. abbreviation).

Feel free to use this or not.

Perhaps the floruit should not be shown if both birth & death are available...?

### CODE REVIEW

**Comment by T-F-S** [comment]
For my own research, I use something like a "common event" to note things like "person mentioned in 1655" which is quite like the "floruit". But I did'nt used any symbol for that until now.

The genealogy symbols which are available with `genealogytree` were created according to traditionally used symbols as denoted in

[Genealogische Symbole und Zeichen](http://wiki-de.genealogy.net/Genealogische_Symbole_und_Zeichen)

or

[Genealogy Symbols](https://www.tamurajones.net/GenealogySymbols.xhtml)

I was not aware of a "floruit" symbol and I was not able to find it using Google.
Do you have a source where this symbol is mentioned or was it invented by you?

Anyway, I like the idea to have such a symbol.

For `database format`, I have to spend some more thinking on where the "floruit" event should be displayed or not...

On technical side, the white circle inside the `tikzpicture` code may cause troubles when using other colors (white for example) - but I think that can be solved by altering the code.

**Comment by mikkelee** [comment]
The flower symbol was invented by me based on the meaning of the latin floruit. I only know the fl. abbreviation, but I thought it looked inconsistent to suddenly use an abbreviation :)

As I mentioned, I'm not very good at tikz, so the symbol itself could definitely be improved as you say. I basically just took the birth symbol & drew a small white circle on top. I also tried to make the leaves of the petal rounded, but couldn't figure out how.

As for db formats, you know best.

**Comment by mikkelee** [comment]
👍 thanks for accepting & cleaning up the symbol/formats. I have just tested my tree with 1.20 from CTAN & it works great! :)

**Comment by T-F-S** [comment]
I'm glad to hear that. Thanks again for inventing the floruit event ;-)

**Comment by mikkelee** [comment]
Showed my father a tree that uses the floruit symbol, and after some confusing questions, we realized that the symbol probably needs to be more clearly different from the birth symbol. Perhaps turning the flower upside down for the next release will be sufficient?

**Comment by T-F-S** [comment]
I will do some tests in that direction.

**Comment by mikkelee** [comment]
I've tested the upside-down symbol locally with `rotate=180` in the `gtr@tikzpicture` options (gtrcore.symbols.code.tex line 169). Much easier to tell the difference in my opinion.

**Comment by T-F-S** [comment]
Yes, I also think that the rotated version is better. You could also image the 270 degree bloom to be the stem of the flower. I will change the code accordingly in the near future.

**Comment by T-F-S** [comment]
The new version 1.21 has the floruit symbol rotated.

**Pull request merged**
